# Generated by Django 4.0.3 on 2022-03-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaaniapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
