# Generated by Django 4.0.3 on 2022-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaaniapp', '0004_business_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='mtaani_description',
            field=models.TextField(null=True),
        ),
    ]
