# Generated by Django 4.0.3 on 2022-03-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaaniapp', '0005_neighbourhood_mtaani_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='mtaani_description',
            field=models.TextField(default='Hallo', null=True),
        ),
    ]
