# Generated by Django 4.0.3 on 2022-03-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaaniapp', '0006_alter_neighbourhood_mtaani_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='mtaani_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
